### ISSUE TITLE
Retrieve the data

### ISSUE THREAD

**Issue by DomSavd** [adlawson/mixcloud-tracklist#10]
First of all thanks for that useful plugin!

I am wondering if it is possible to retrieve the data for example as a json file?

Thanks for your help.

**Comment by adlawson** [comment]
Hey @DomSavd, it shouldn't be a problem to get track data in JSON.
There's an undocumented API endpoint that this plugin uses and Mixcloud themselves use to populate the titles in the player bar.

You can see the data at `https://www.mixcloud.com/player/details/?key=SOME_KEY` where the `SOME_KEY` is the path of the mix URL. For example, the data for the mix at https://www.mixcloud.com/theblackdog/radio-dogma-50/ is at https://www.mixcloud.com/player/details/?key=%2Ftheblackdog%2Fradio-dogma-50%2F.

You can see this plugin using it at https://github.com/adlawson/mixcloud-tracklist/blob/a1f2331350368466887e13a1886a7ab7b9113957/tracklist.js#L65

I hope that helps. Happy hacking!
