### ISSUE TITLE
Tracklist longer than drop-down pane does display entire tracklist.

### ISSUE THREAD

**Issue by batsonjay** [adlawson/mixcloud-tracklist#13]
Example: The tracklist on this page was longer than would show when I clicked "Show Tracklist". It showed the first 10 items, but could not display any more. There should be some way to scroll, or display the remainder of the tracklist.

https://www.mixcloud.com/Hot_Since_82/hot-since-82-summer-hotcast-13/

**Comment by adlawson** [comment]
I checked out the tracklist data for that mix and it only contains the first 10 (see below).
In contrast, [here's a mix](https://www.mixcloud.com/kingstonpork/epochs-fables-vol257/) that has a lot more than 10 tracks listed and displays them correctly.

I guess the uploader of the mix you saw hadn't listed them all.

```
{
  "favorite_url":"/favorites/Hot_Since_82/hot-since-82-summer-hotcast-13/",
  "add_to_collection_popover_url":"/playlists/Hot_Since_82/hot-since-82-summer-hotcast-13/add-to-collection-popover/?source_detail=Player",
  "juno":{
    "chart_url":"http://www.junodownload.com/charts/mixcloud/Hot_Since_82/hot-since-82-summer-hotcast-13/37526078",
    "guid":"82A04B0D-8F08-49D4-8728-45043A49C90F",
    "replace_tracklist":false
  },
  "follow_url":"/Hot_Since_82/follow/",
  "comment_post_url":"/comments/cloudcast/Hot_Since_82/hot-since-82-summer-hotcast-13/post/",
  "follow_back":false,
  "is_reposted":false,
  "repost_url":"/repost/Hot_Since_82/hot-since-82-summer-hotcast-13/",
  "favorite_chained_action":"/chained/favorite/Hot_Since_82/hot-since-82-summer-hotcast-13/",
  "hide_follow":false,
  "is_following":false,
  "is_favorited":false,
  "lastfm":{
    "scrobble":false
  },
  "waveform_url":"https://waveform.mixcloud.com/7/d/5/1/6f52-0c15-4b0c-b407-d304ca9a071b.json?v=0.1",
  "listen_chained_action":"/chained/listen/Hot_Since_82/hot-since-82-summer-hotcast-13/",
  "should_hide_tracklist":true,
  "share_dialog_url":"/share-dialog/cloudcast/Hot_Since_82/hot-since-82-summer-hotcast-13/",
  "cloudcast":{
    "owner_name":"Hot Since 82",
    "more_featuring_artists":true,
    "featuring_artist_list":[
      "Claire Riley",
      "UJIN",
      "Julian Chaptal",
      "Noir & Haze",
      "Jacob Husley"
    ],
    "hovercard_url":"/Hot_Since_82/hovercard-modal/",
    "audio_length":7038,
    "id":37526078,
    "title":"Hot Since 82 - Summer Hotcast '13",
    "url":"/Hot_Since_82/hot-since-82-summer-hotcast-13/",
    "pictures":{
      "mobile_player_full":"https://thumbnailer.mixcloud.com/unsafe/300x300/extaudio/1/a/e/5/ba41-80cd-4cb1-adef-8775529e4bc0.jpg",
      "widget":"https://thumbnailer.mixcloud.com/unsafe/180x180/extaudio/1/a/e/5/ba41-80cd-4cb1-adef-8775529e4bc0.jpg",
      "mobile_player_bar":"https://thumbnailer.mixcloud.com/unsafe/35x35/extaudio/1/a/e/5/ba41-80cd-4cb1-adef-8775529e4bc0.jpg",
      "www_thumbnail":"https://thumbnailer.mixcloud.com/unsafe/60x60/extaudio/1/a/e/5/ba41-80cd-4cb1-adef-8775529e4bc0.jpg"
    },
    "owner_url":"/Hot_Since_82/",
    "primary_color":"26142b",
    "sections":[
      {
        "start_time":null,
        "artist":"No Artificial Colours feat. Alex Mills",
        "title":"Crying Wolf"
      },
      {
        "start_time":null,
        "artist":"Claire Riley",
        "title":"Slow Loris"
      },
      {
        "start_time":null,
        "artist":"Noir & Haze",
        "title":"Around"
      },
      {
        "start_time":null,
        "artist":"Luca bacchetti",
        "title":"On The Moon With You"
      },
      {
        "start_time":null,
        "artist":"UJIN",
        "title":"It's All Good"
      },
      {
        "start_time":null,
        "artist":"Quardo Rossi",
        "title":"DEEP STORY"
      },
      {
        "start_time":null,
        "artist":"Julian Chaptal",
        "title":"Elephants On A String"
      },
      {
        "start_time":null,
        "artist":"Jacob Husley",
        "title":"I Got Sunshine"
      },
      {
        "start_time":null,
        "artist":"Marlose",
        "title":"Avantgardistisch (Marc DePulse Remix)"
      },
      {
        "start_time":null,
        "artist":"Andhim ",
        "title":"Alter Egon"
      }
    ]
  }
}
```

**Comment by batsonjay** [comment]
Looks like you’re right, and I posted a non-issue.

Thanks!
-jb

> On Jul 13, 2016, at 9:16 AM, Andrew Lawson notifications@github.com wrote:
> 
> I checked out the tracklist data for that mix and it only contains the first 10 (see below).
> In contrast, here's a mix https://www.mixcloud.com/kingstonpork/epochs-fables-vol257/ that has a lot more than 10 tracks listed and displays them correctly.
> 
> I guess the uploader of the mix you saw hadn't listed them all.
> 
> {
>   "favorite_url":"/favorites/Hot_Since_82/hot-since-82-summer-hotcast-13/",
>   "add_to_collection_popover_url":"/playlists/Hot_Since_82/hot-since-82-summer-hotcast-13/add-to-collection-popover/?source_detail=Player",
>   "juno":{
>     "chart_url":"http://www.junodownload.com/charts/mixcloud/Hot_Since_82/hot-since-82-summer-hotcast-13/37526078",
>     "guid":"82A04B0D-8F08-49D4-8728-45043A49C90F",
>     "replace_tracklist":false
>   },
>   "follow_url":"/Hot_Since_82/follow/",
>   "comment_post_url":"/comments/cloudcast/Hot_Since_82/hot-since-82-summer-hotcast-13/post/",
>   "follow_back":false,
>   "is_reposted":false,
>   "repost_url":"/repost/Hot_Since_82/hot-since-82-summer-hotcast-13/",
>   "favorite_chained_action":"/chained/favorite/Hot_Since_82/hot-since-82-summer-hotcast-13/",
>   "hide_follow":false,
>   "is_following":false,
>   "is_favorited":false,
>   "lastfm":{
>     "scrobble":false
>   },
>   "waveform_url":"https://waveform.mixcloud.com/7/d/5/1/6f52-0c15-4b0c-b407-d304ca9a071b.json?v=0.1",
>   "listen_chained_action":"/chained/listen/Hot_Since_82/hot-since-82-summer-hotcast-13/",
>   "should_hide_tracklist":true,
>   "share_dialog_url":"/share-dialog/cloudcast/Hot_Since_82/hot-since-82-summer-hotcast-13/",
>   "cloudcast":{
>     "owner_name":"Hot Since 82",
>     "more_featuring_artists":true,
>     "featuring_artist_list":[
>       "Claire Riley",
>       "UJIN",
>       "Julian Chaptal",
>       "Noir & Haze",
>       "Jacob Husley"
>     ],
>     "hovercard_url":"/Hot_Since_82/hovercard-modal/",
>     "audio_length":7038,
>     "id":37526078,
>     "title":"Hot Since 82 - Summer Hotcast '13",
>     "url":"/Hot_Since_82/hot-since-82-summer-hotcast-13/",
>     "pictures":{
>       "mobile_player_full":"https://thumbnailer.mixcloud.com/unsafe/300x300/extaudio/1/a/e/5/ba41-80cd-4cb1-adef-8775529e4bc0.jpg",
>       "widget":"https://thumbnailer.mixcloud.com/unsafe/180x180/extaudio/1/a/e/5/ba41-80cd-4cb1-adef-8775529e4bc0.jpg",
>       "mobile_player_bar":"https://thumbnailer.mixcloud.com/unsafe/35x35/extaudio/1/a/e/5/ba41-80cd-4cb1-adef-8775529e4bc0.jpg",
>       "www_thumbnail":"https://thumbnailer.mixcloud.com/unsafe/60x60/extaudio/1/a/e/5/ba41-80cd-4cb1-adef-8775529e4bc0.jpg"
>     },
>     "owner_url":"/Hot_Since_82/",
>     "primary_color":"26142b",
>     "sections":[
>       {
>         "start_time":null,
>         "artist":"No Artificial Colours feat. Alex Mills",
>         "title":"Crying Wolf"
>       },
>       {
>         "start_time":null,
>         "artist":"Claire Riley",
>         "title":"Slow Loris"
>       },
>       {
>         "start_time":null,
>         "artist":"Noir & Haze",
>         "title":"Around"
>       },
>       {
>         "start_time":null,
>         "artist":"Luca bacchetti",
>         "title":"On The Moon With You"
>       },
>       {
>         "start_time":null,
>         "artist":"UJIN",
>         "title":"It's All Good"
>       },
>       {
>         "start_time":null,
>         "artist":"Quardo Rossi",
>         "title":"DEEP STORY"
>       },
>       {
>         "start_time":null,
>         "artist":"Julian Chaptal",
>         "title":"Elephants On A String"
>       },
>       {
>         "start_time":null,
>         "artist":"Jacob Husley",
>         "title":"I Got Sunshine"
>       },
>       {
>         "start_time":null,
>         "artist":"Marlose",
>         "title":"Avantgardistisch (Marc DePulse Remix)"
>       },
>       {
>         "start_time":null,
>         "artist":"Andhim ",
>         "title":"Alter Egon"
>       }
>     ]
>   }
> }
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub https://github.com/adlawson/mixcloud-tracklist/issues/13#issuecomment-232351357, or mute the thread https://github.com/notifications/unsubscribe/AAhth-ipf7LsDwAKaAqZK8fPtKUOAfPDks5qVOVEgaJpZM4JLWFR.

---

Jay Batson

batsonjay@gmail.com mailto:batsonjay@gmail.com
Mobile: +1-978-758-1599
Blog: http://startupdj.com http://startupdj.com/
Twitter: @jab http://twitter.com/jab
Schedule time to meet or talk http://doodle.com/batsonjay
