### ISSUE TITLE
Large margin above tracklist

### ISSUE THREAD

**Issue by adlawson** [adlawson/mixcloud-tracklist#19]
The tracklist on Mixcloud's new (Beta) website is displayed with a large margin above it (see white space in the first image below). This seems to be due to the `clear:both` I've applied to it.

![image 1](https://cloud.githubusercontent.com/assets/200351/20041135/e9d64642-a45c-11e6-887c-f30575a64852.png)

The problem is that without the `clear:both` the tracklist is restricted to the main content side of the page which looks even worse.

![image 2](https://cloud.githubusercontent.com/assets/200351/20041144/feaa1ddc-a45c-11e6-9fe3-51cf18519e76.png)

Applying rubbish workarounds like `margin-top:-20px` etc doesn't seem to help.

**Comment by adlawson** [comment]
I'd appreciate some help on this one, so here's some instructions for running it (in Chrome) if you'd like to give me a hand:

**1) Extract this Zip somewhere on your local machine**
[mixcloud-tracklist.zip](https://github.com/adlawson/mixcloud-tracklist/files/574130/mixcloud-tracklist.zip)

---

**2) Make sure you disable any other versions of this extension you're running**
![image 1](https://cloud.githubusercontent.com/assets/200351/20041452/32876750-a461-11e6-913f-056efbe0e476.png)

---

**3) Enable "Developer Mode" in [chrome://extensions](chrome://extensions)**
![image 2](https://cloud.githubusercontent.com/assets/200351/20041421/c099e492-a460-11e6-83d1-d2ed5869f485.png)

---

**4) Click "Load unpacked extension..." and point it to the unzipped folder from step 1.** Don't worry about the "unrecognised manifest key 'application'" warning
![image](https://cloud.githubusercontent.com/assets/200351/20041471/7057645e-a461-11e6-9d80-3b7b6f072e05.png)

**Comment by perryharlock** [comment]
Add this to `.cloudcast-tracklist`
`position: relative;
    top: -42px;`

![image](https://cloud.githubusercontent.com/assets/1225142/20050920/0d986062-a4c4-11e6-84d4-7330f106f4aa.png)
