### ISSUE TITLE
API changes break tracklist functionality

### ISSUE THREAD

**Issue by adlawson** [adlawson/mixcloud-tracklist#32]
Calls to `player/details?key=blah` are now responding with a `301` redirect to `player/details/?key=blah` (with trailing slash after `details`) and the extension is not following it.

This was spotted while debugging #31.

**Comment by adlawson** [comment]
I think this is actually a bigger change than the redirect. It appears that there are further changes, and a possible introduction of a CSRF Token that stops the tracklist working.

I'll continue to investigate and try to get this fixed. I'm confident it's fixable, but I just need to work out what to change in the request.

**Comment by zygisber** [comment]
Is this due to changes in mixcloud or player? Where do you get info about
API?

**Comment by adlawson** [comment]
Yeah this is a change by Mixcloud. I'm just investigating their APIs and considering how it's changed compared to how it used to behave. These are internal APIs used by Mixcloud so I doubt we'd find any public documentation about it.

**Comment by adlawson** [comment]
I've now proven that all I need to do is send the cookies with the request to the API. It's absolutely possible to do it, but I'll try a few different ideas before complicating the extension with an event/background script.

**Comment by zygisber** [comment]
It is good to know theres a sollution, but how do you come to those ideas?
:) How to format cookie, how to send? :)
Z.

**Comment by adlawson** [comment]
@zygisber I've used `fetch` rather than the `request` library to send the requests now. This way the browser can slurp up the cookies and send them without much intervention.

If that hadn't have worked, I'd have had to go down the route of using [`chrome.cookies`](https://developer.chrome.com/extensions/cookies) in a background script and sending messages to the content script (where the extension runs). Fortunately I don't have to do any of that 🎉
