### ISSUE TITLE
Tracklist is not displayed

### ISSUE THREAD

**Issue by catalin-florescu** [adlawson/mixcloud-tracklist#33]
Tracklist is no more displayed, but in player song appears. Does API changed?

**Comment by zygisber** [comment]
function fetchData(location, fn) {
    request({
        "uri": "/player/details",
        "baseUrl": location.protocol + "//" + location.hostname,
        "qs": { "key": location.pathname },
        "json": true
    }, function (error, response, data) {
        if (!error && response.statusCode === 200 &&
data.cloudcast.sections.length > 0) {
            fn(insertTrackNumber(data));
        } else {
            console.error(error);
        }
    });
}

Now request returns response.statusCode = 200 everytime.

**Comment by catalin-florescu** [comment]
@zygisber I'm not familiar with JS, can you explain what to do?

**Comment by adlawson** [comment]
Duplicate of #32
