### ISSUE TITLE
Any possibility of a Safari version?

### ISSUE THREAD

**Issue by patrickrushton** [adlawson/mixcloud-tracklist#8]
I've heard it's fairly straightforward to convert Firefox Add Ons to Safari Extensions, but wouldn't know where to begin myself.

**Comment by adlawson** [comment]
I'll add it to the list of things to do.
Thanks :+1:

**Comment by patrickrushton** [comment]
Any news on a Safari version, or perhaps a userscript that can be installed via tampermonkey?

**Comment by adlawson** [comment]
Hey @patrickrushton, it's been a while but I've finally pulled my finger out.

https://gist.github.com/adlawson/147e22f20e6f1eeb75c8e37acc19c96c (Link is also in the README of this project).

It's not pretty as it's mostly put together from bits and pieces of the browser extension code but it should work fine. I've tested it in both Firefox and Chrome but I don't have access to Safari on my machine.

Let me know if you have any problems with it.

**Comment by adlawson** [comment]
Oh I should mention that it doesn't include the "playerbar" bit; only the Tracklist button in the centre of the page. I think Mixcloud have removed the playerbar feature altogether but I'm not sure how much people miss it.

**Comment by patrickrushton** [comment]
Thanks for looking at this. Unfortunately I'm not seeing the tracklist button at all. Tampermonkey wasn't reporting the script as running when on mixcloud, so I tried adding a line
`// @include         https://www.mixcloud.com/*`

No Tampermonkey at least reports the script as active when on the site, but still not tracklist button.

**Comment by adlawson** [comment]
Hm that's strange. I'm on my work laptop now so I've managed to test it in Safari (Version 10.0 (11602.1.50.0.10)). Worked without modification.

Maybe the mix you were on didn't have a tracklist submitted? Could you check out the mix I was on in the screenshot below? https://www.mixcloud.com/Halftribe/2k/

![image](https://cloud.githubusercontent.com/assets/200351/18831215/6853e886-83dc-11e6-812c-b95698b806f6.png)

**Comment by patrickrushton** [comment]
Strangely it's suddenly started working. Also on the mix I was originally trying https://www.mixcloud.com/hayhook/global-communication-universal-language-chilled-mix-3/

And Tampermonkey correctly reports the script as active without the the extra line I added. 

So I think you can ignore my earlier comment. Good taste in mixes btw. ;-)

**Comment by adlawson** [comment]
Oh good, I'm glad it's working!
Again, sorry it took me so long to get something sorted but hopefully now you can enjoy Mixcloud the way it used to be 😄
